on:
  push:
    tags:
      - 'v1.*.*'
      - '!v1'

jobs:
  test:
    name: Bruker action fra dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: erstatningersteg
        uses: ./
        with:
          sok: '{VERSJON}'
          erstatt: 'v1.2.3'
          filer: './testfiler/**/*.js'
          dry-run: true
      - run: echo "Antall erstatninger ${{ steps.erstatningersteg.outputs.antall }}"

  bygg:
    # name: Node ${{ matrix.node_version }} - Bygg, test og lint
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix: # Tester ut å bruke både Node.js 12 og 14.
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm test
          npm run lint
          npm run build
